- name: Removing all printers and classes on server.
  cups_lpadmin:
    purge: True
  when: cups_purge_all_printers_and_classes

- name: Install printers using cups_lpadmin
  cups_lpadmin:
    name: "{{item.name}}"
    printer_or_class: "printer"
    state: "{{item.state|default(cups_printer_default_state)}}"
    enabled: "{{item.enabled|default(cups_printer_default_enabled)}}"
    uri: "{{cups_printer_uri_prefix}}{{item.uri}}"
    default: "{{item.default_printer|default(omit)}}"
    model: "{{item.driver|default(omit)}}"
    location: "{{item.location|default(omit)}}"
    info: "{{item.info|default(omit)}}"
    report_ipp_supply_levels: "{{item.report_ipp_supply_levels|default(cups_printer_default_report_ipp_supplies)}}"
    report_snmp_supply_levels: "{{item.report_snmp_supply_levels|default(cups_printer_default_report_snmp_supplies)}}"
    shared: "{{item.shared|default(cups_printer_default_is_shared)}}"
    assign_cups_policy: "{{item.assign_cups_policy|default(cups_printer_default_assign_cups_policy)}}"
    job_kb_limit: "{{item.job_kb_limit|default(omit)}}"
    job_quota_limit: "{{item.job_quota_limit|default(omit)}}"
    job_page_limit: "{{item.job_page_limit|default(omit)}}"
    options: "{{item.options|default(omit)}}"
  with_items:
    - "{{cups_printer_list}}"